apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: agent-operator
  labels:
    app: agent-operator
subjects:
  - kind: ServiceAccount
    name: agent-operator
    namespace: agent
roleRef:
  kind: ClusterRole
  name: agent-operator
  apiGroup: rbac.authorization.k8s.io