apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: agent-operator
  labels:
    app: agent-operator
rules:
  # the Java operator SDK seems to list CRDs
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - managedkafka.bf2.org
    resources:
      - managedkafkas
      - managedkafkas/status
    verbs:
      - get
      - list
      - watch
      - patch
      - update
  - apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkas
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkas
      - kafkas/status
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - apps
    resources:
      - deployments
      - deployments/status
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - extensions
    resources:
      - deployments
      - deployments/status
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update