---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: agent-operator
rules:
  - apiGroups:
      - managedkafka.bf2.org
    resources:
      - "*"
      - "*/finalizers"
    verbs: [get, list, create, update, delete, deletecollection, watch]
  - apiGroups:
      - ""
    resources:
      - pods
      - services
      - endpoints
      - persistentvolumeclaims
      - configmaps
      - secrets
      - serviceaccounts
    verbs: [get, list, create, update, delete, deletecollection, watch]
  - apiGroups:
      - ""
    resources:
      - replicationcontrollers
      - replicationcontrollers/scale
    verbs: [get, list, create, update, delete, deletecollection, watch, patch]
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - deployments
      - deployments/scale
      - replicasets
      - replicasets/scale
      - statefulsets
      - statefulsets/scale
    verbs: [get, list, create, update, delete, deletecollection, watch, patch]
  - apiGroups:
      - extensions
    resources:
      - daemonsets
      - deployments
      - deployments/scale
      - ingresses
      - networkpolicies
      - replicasets
      - replicasets/scale
      - replicationcontrollers/scale
    verbs: [get, list, create, update, delete, deletecollection, watch, patch]
  - apiGroups:
      - ""
    resources:
      - bindings
      - events
      - limitranges
      - namespaces/status
      - pods/log
      - pods/status
      - replicationcontrollers/status
      - resourcequotas
      - resourcequotas/status
    verbs: [get, list, watch]
  - apiGroups:
      - ""
      - apps.openshift.io
    resources:
      - deploymentconfigs
      - deploymentconfigs/scale
    verbs: [get, list, create, update, delete, deletecollection, watch, patch]
  - apiGroups:
      - ""
      - apps.openshift.io
    resources:
      - deploymentconfigrollbacks
      - deploymentconfigs/instantiate
      - deploymentconfigs/rollback
    verbs: [create]
  - apiGroups:
      - ""
      - apps.openshift.io
    resources:
      - deploymentconfigs/log
      - deploymentconfigs/status
    verbs: [get, list, watch]
  - apiGroups:
      - ""
    resources:
      - events
    verbs: [get, list]
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs: [get, list, create, update, delete, deletecollection, watch]
  - apiGroups:
      - ""
      - template.openshift.io
    resources:
      - processedtemplates
      - templateconfigs
      - templateinstances
      - templates
    verbs: [get, list, create, update, delete, deletecollection, watch, patch]
  - apiGroups:
      - authorization.openshift.io
    resources:
      - rolebindings
    verbs: [get, list, create, update, delete, deletecollection, watch]
  - apiGroups:
      - route.openshift.io
    resources:
      - routes
      - routes/custom-host
    verbs: [get, list, create, update, delete, deletecollection, watch, patch]
  - apiGroups:
      - kafka.strimzi.io
    resources:
      - kafkas
      - kafka
    verbs: [get, list, create, update, delete, deletecollection, watch]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: agent-operator
subjects:
- kind: ServiceAccount
  name: agent-operator
roleRef:
  kind: Role
  name: agent-operator
  apiGroup: rbac.authorization.k8s.io
---
