name: kas-fleetshard
release:
  # The values here will usually be stale on the main branch.  This is
  # intentional -- they should only be updated by creating a PR to the
  # release branch.
  current-version: 0.10.1
  next-version: 0.10.2-SNAPSHOT
