kind: ConfigMap
apiVersion: v1
metadata:
  name: zookeeper-metrics
data:
  jmx-exporter-config: |
    lowercaseOutputName: true
    rules:
      # begin SLI-Defined metrics
      - pattern: org.apache.ZooKeeperService<(name0=ReplicatedServer_id(\d+), name1=replica.(\d+), name2=(\w+))><>OutstandingRequests
        name: zookeeper_outstanding_requests
        type: GAUGE
        labels:
          replicaId: "$2"
          memberType: "$3"
      - pattern: org.apache.ZooKeeperService<(name0=ReplicatedServer_id(\d+), name1=replica.(\d+), name2=(\w+))><>AvgRequestLatency
        name: zookeeper_avg_request_latency
        type: GAUGE
        labels:
          replicaId: "$2"
          memberType: "$3"
      - pattern: org.apache.ZooKeeperService<(name0=ReplicatedServer_id(\d+))><>QuorumSize
        name: zookeeper_quorum_size
        type: GAUGE
      # begin additional required metrics for upstream dashboards
      - pattern: org.apache.ZooKeeperService<(name0=ReplicatedServer_id(\d+), name1=replica.(\d+), name2=(\w+))><>NumAliveConnections
        name: zookeeper_num_alive_connections
        type: GAUGE
        labels:
          replicaId: "$2"
          memberType: "$3"
      - pattern: org.apache.ZooKeeperService<(name0=ReplicatedServer_id(\d+), name1=replica.(\d+), name2=(\w+), name3=InMemoryDataTree)><>NodeCount
        name: zookeeper_in_memory_data_tree_node_count
        type: GAUGE
        labels:
          replicaId: "$2"
          memberType: "$3"
      - pattern: org.apache.ZooKeeperService<(name0=ReplicatedServer_id(\d+), name1=replica.(\d+), name2=(\w+), name3=InMemoryDataTree)><>WatchCount
        name: zookeeper_in_memory_data_tree_watch_count
        type: GAUGE
        labels:
          replicaId: "$2"
          memberType: "$3"
      - pattern: org.apache.ZooKeeperService<(name0=ReplicatedServer_id(\d+), name1=replica.(\d+), name2=(\w+))><>MinRequestLatency
        name: zookeeper_min_request_latency
        type: GAUGE
        labels:
          replicaId: "$2"
          memberType: "$3"
      - pattern: org.apache.ZooKeeperService<(name0=ReplicatedServer_id(\d+), name1=replica.(\d+), name2=(\w+))><>MaxRequestLatency
        name: zookeeper_max_request_latency
        type: GAUGE
        labels:
          replicaId: "$2"
          memberType: "$3"