apiVersion: v1
kind: Template
metadata:
  name: sharded-template
objects:
- apiVersion: operator.openshift.io/v1
  kind: IngressController
  metadata:
    name: sharded
  spec:
    domain: ${DOMAIN}
    routeSelector:
      matchLabels:
        ingressType: sharded
    replicas: ${{REPLICAS}}
parameters:
- description: Domain
  name: DOMAIN
- description: Replicas
  name: REPLICAS
  value: "2"
