kind: ConfigMap
apiVersion: v1
metadata:
  name: zookeeper-logging
  labels:
    app: strimzi
data:
  log4j.properties: |
    log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender

    log4j.appender.CONSOLE.layout=org.apache.log4j.EnhancedPatternLayout

    log4j.appender.CONSOLE.layout.ConversionPattern=%d{yyyy-MM-dd'T'HH:mm:ss'Z'}{GMT} %-5p [%t] [%c{1}] %m%n

    zookeeper.root.logger=INFO

    log4j.rootLogger=${zookeeper.root.logger}, CONSOLE