kind: ConfigMap
apiVersion: v1
metadata:
  name: zookeeper-logging
  labels:
    app: strimzi
data:
  log4j.properties: |
    log4j.appender.CONSOLE=org.apache.log4j.ConsoleAppender

    log4j.appender.CONSOLE.layout=org.apache.log4j.PatternLayout

    log4j.appender.CONSOLE.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss}{GMT} %-5p [%t] [%c{1}:%L] %m%n

    zookeeper.root.logger=INFO

    log4j.rootLogger=${zookeeper.root.logger}, CONSOLE