---
apiVersion: k8s.keycloak.org/v2alpha1
kind: KeycloakRealmImport
metadata:
  name: demo-realm
spec:
  keycloakCRName: keycloak
  realm:
    id: demo
    realm: demo
    displayName: demo
    description: 'kas-fleetshard-systemtests: demo'
    enabled: true
    clients:
      - clientId: kafka
        description: "kas-fleetshard-systemtests: kafka client"
        secret: kafka
        name: kafka
        serviceAccountsEnabled: true
        protocol: openid-connect
        publicClient: false
        clientAuthenticatorType: client-secret
