apiVersion: keycloak.org/v1alpha1
kind: Keycloak
metadata:
  name: example-keycloak
  labels:
    app: sso
spec:
  instances: 1
  extensions:
    - https://github.com/aerogear/keycloak-metrics-spi/releases/download/1.0.4/keycloak-metrics-spi-1.0.4.jar
  externalAccess:
    enabled: False
  podDisruptionBudget:
    enabled: True
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakRealm
metadata:
  name: demo
  labels:
    app: demo
spec:
  realm:
    id: "demo"
    realm: "demo"
    enabled: True
    displayName: "demo"
  instanceSelector:
    matchLabels:
      app: sso
---
apiVersion: keycloak.org/v1alpha1
kind: KeycloakClient
metadata:
  name: kafka
  labels:
    app: sso
spec:
  realmSelector:
    matchLabels:
      app: demo
  client:
    clientId: kafka
    secret: kafka
    clientAuthenticatorType: client-secret
    protocol: openid-connect
    serviceAccountsEnabled: true
    standardFlowEnabled: false
    implicitFlowEnabled: false