apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kas-fleetshard-operator
  labels:
    app: kas-fleetshard-operator
subjects:
  - kind: ServiceAccount
    name: kas-fleetshard-operator
    namespace: kas-fleetshard
  - kind: ServiceAccount
    name: kas-fleetshard-sync
    namespace: kas-fleetshard
roleRef:
  kind: ClusterRole
  name: kas-fleetshard-operator
  apiGroup: rbac.authorization.k8s.io