apiVersion: v1
kind: ServiceAccount
metadata:
  name: kas-fleetshard-operator
  labels:
    app: kas-fleetshard-operator
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kas-fleetshard-sync
  labels:
    app: kas-fleetshard-sync