apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kas-fleetshard-sync
  labels:
    app: kas-fleetshard-sync
rules:
  - apiGroups:
      - managedkafka.bf2.org
    resources:
      # sync resources for getting Kafka instance to deploy, configuration and reporting back status
      - managedkafkas
      - managedkafkas/status
      - managedkafkaagents
      - managedkafkaagents/status
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      # sync has to create namespaces for Kafka instances to deploy
      - namespaces
    verbs:
      - get
      - list
      - create
      - delete
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kas-fleetshard-sync
  labels:
    app: kas-fleetshard-sync
subjects:
  - kind: ServiceAccount
    name: kas-fleetshard-sync
    namespace: kas-fleetshard
roleRef:
  kind: ClusterRole
  name: kas-fleetshard-sync
  apiGroup: rbac.authorization.k8s.io
# secret permission is generated by quarkus-kubernetes-config in the main deployment file
# https://github.com/quarkusio/quarkus/issues/15279 addresses that the permissions are too broad
---
