# This workflow will build a Java project with Maven

name: Build and Unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.2
    - name: Build and run Unit tests
      run: mvn -B package --file pom.xml --no-transfer-progress
