# This workflow will build a Java project with Maven

name: Build and Unit tests

on:
  push:
    branches:
      - 'main'
      - "[0-9]+.[0-9]+.x"
  pull_request:
    branches:
      - 'main'
      - "[0-9]+.[0-9]+.x"
    types: [ opened, reopened, synchronize ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
    - name: Cache m2 repo
      uses: actions/cache@v1
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Build and run Unit tests
      run: mvn install --file pom.xml --no-transfer-progress -Dno-format
    - name: Save Build Context
      run: echo "$GITHUB_CONTEXT" > target/build-context.json
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
    - name: Attach Build Output
      uses: actions/upload-artifact@v2
      with:
        name: target
        path: |
          target/
          api/target/
          common/target/
          operator/target/
          sync/target/
