# This workflow will build a Java project with Maven

name: Publish Artifacts

on:
  release:
    types:
      - created
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: temurin

    - name: Cache m2 repo
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Deploy Artifacts
      run: mvn deploy -Pquickly --no-transfer-progress -Dno-format
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
