# This workflow will build a Java project with Maven

name: Publish Artifacts

on:
  release:
    types:
      - created
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: 11
        distribution: 'temurin'
        cache: 'maven'

    - name: Deploy Artifacts
      run: mvn deploy -Pquickly --no-transfer-progress -Dno-format
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
