name: Release

on:
  pull_request:
    types: [closed]
    paths:
      - '.github/project.yml'

jobs:
  release:
    runs-on: ubuntu-latest
    name: release
    if: ${{github.event.pull_request.merged == true}}
    env:
      GITHUB_TOKEN: ${{secrets.BF2ROBOT_TOKEN}}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          token: ${{secrets.BF2ROBOT_TOKEN}}

      - name: Retrieve Project Metadata
        uses: radcortez/project-metadata-action@243817f1e0f2b4df4e012fc17efc45cff166425d
        id: metadata
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          metadata-file-path: '.github/project.yml'
          local-file: true

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'

      - name: Perform Maven Release
        run: |
          git config --global user.name "bf2robot"
          git config --global user.email "bf2-admin+bf2robot@redhat.com"
          # Prepare release and tag repository on the pull request's merge branch (e.g. `refs/pull/123/merge`)
          mvn -B -P release release:prepare -DreleaseVersion=${{steps.metadata.outputs.current-version}} -DdevelopmentVersion=${{steps.metadata.outputs.next-version}} -DignoreSnapshots=true
          # Switch to the target branch of the pull request (e.g. `main`) and fast-forward to the results of the release:prepare task
          git checkout ${{github.base_ref}}
          git rebase ${{github.ref}}
          export QUARKUS_CONTAINER_IMAGE_REGISTRY="${{secrets.IMAGE_REPO_HOSTNAME}}"
          export QUARKUS_CONTAINER_IMAGE_GROUP="${{secrets.IMAGE_REPO_NAMESPACE}}"
          export QUARKUS_CONTAINER_IMAGE_USERNAME="${{secrets.IMAGE_REPO_USERNAME}}"
          export QUARKUS_CONTAINER_IMAGE_PASSWORD="${{secrets.IMAGE_REPO_PASSWORD}}"
          # Build and push the release images using the commit tagged in `release:prepare`
          mvn -B -P release release:perform

      - name: Push Release Tag
        run: |
          git push
          git push --tags

      - name: Create GitHub Release
        uses: radcortez/milestone-release-action@98bd3321583e9bdbbe15c08fa4b2249371efaeaa
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          milestone-title: ${{steps.metadata.outputs.current-version}}
