name: Smoke tests
on:
  push:
    branches:
      - 'main'
      - "[0-9]+.[0-9]+.x"
  pull_request:
    branches:
      - 'main'
      - "[0-9]+.[0-9]+.x"
    types: [ opened, reopened, synchronize ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        if: github.event_name == 'pull_request'
        uses: styfle/cancel-workflow-action@0.12.0

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: 'temurin'
          cache: 'maven'

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.7.2
        with:
          minikube version: 'v1.24.0'
          kubernetes version: 'latest'
          start args: '--addons=registry,storage,ingress --insecure-registry "10.0.0.0/24" --insecure-registry "localhost:5000" --extra-config=kubeadm.ignore-preflight-errors=SystemVerification --extra-config=apiserver.authorization-mode=RBAC,Node'

      - name: Build and push images
        run: |
          mvn package -pl operator,sync -am -Pimage-test-push --no-transfer-progress -Dquarkus.kubernetes.resources.requests.cpu=50m -Dquarkus.kubernetes.resources.requests.memory=128Mi

      - name: Run smoke test
        run: |
          mvn verify -P systemtest -pl systemtest -Dgroups=smoke -am --no-transfer-progress

      - name: Archive results
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: artifacts
          path: systemtest/target/logs/
