name: Smoke tests
on:
  push:
    branches:
      - 'main'
      - "[0-9]+.[0-9]+.x"
  pull_request:
    branches:
      - 'main'
      - "[0-9]+.[0-9]+.x"
    types: [ opened, reopened, synchronize ]

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.3.1
        with:
          minikube version: 'v1.18.1'
          kubernetes version: 'latest'
          start args: '--addons=registry --insecure-registry "10.0.0.0/24" --insecure-registry "localhost:5000" --extra-config=kubeadm.ignore-preflight-errors=SystemVerification --extra-config=apiserver.authorization-mode=RBAC,Node'

      - name: Build and push operator
        run: |
          mvn package -pl operator -am -P quickly --no-transfer-progress \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.group=bf2 \
          -Dquarkus.container-image.name=kas-fleetshard-operator \
          -Dquarkus.container-image.tag=latest \
          -Dquarkus.container-image.registry=localhost:5000 \
          -Dquarkus.container-image.insecure=true \
          -Dkafka=dev \
          -Dquarkus.profile=test

      - name: Build and push sync
        run: |
          mvn package -pl sync -am -P quickly --no-transfer-progress \
          -Dquarkus.container-image.build=true \
          -Dquarkus.container-image.push=true \
          -Dquarkus.container-image.group=bf2 \
          -Dquarkus.container-image.name=kas-fleetshard-sync \
          -Dquarkus.container-image.tag=latest \
          -Dquarkus.container-image.registry=localhost:5000 \
          -Dquarkus.container-image.insecure=true \
          -Dkafka=dev \
          -Dquarkus.profile=test

      - name: Run smoke test
        run: |
          mvn verify -P systemtest -pl systemtest -Dgroups=smoke -am --no-transfer-progress \
            -Djunit.jupiter.execution.parallel.enabled=true \
            -Djunit.jupiter.execution.parallel.config.fixed.parallelism=2

      - name: Archive results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: artifacts
          path: systemtest/target/logs/
