name: Integration tests
on:
  pull_request:
    types: [ labeled ]

jobs:
  test:
    if: ${{ github.event.label.name == 'run-all-tests' }}
    runs-on: ubuntu-latest
    steps:
      - name: Cancel Previous Runs
        if: github.event_name == 'pull_request'
        uses: styfle/cancel-workflow-action@0.9.1

      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: Cache m2 repo
        uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Setup Minikube
        uses: manusa/actions-setup-minikube@v2.4.2
        with:
          minikube version: 'v1.24.0'
          kubernetes version: 'latest'
          start args: '--addons=registry,storage,ingress --insecure-registry "10.0.0.0/24" --insecure-registry "localhost:5000" --extra-config=kubeadm.ignore-preflight-errors=SystemVerification --extra-config=apiserver.authorization-mode=RBAC,Node'

      - name: Build and push images
        run: |
          mvn package -pl operator,sync -am -Pimage-test-push --no-transfer-progress -Dquarkus.kubernetes.resources.requests.cpu=50m -Dquarkus.kubernetes.resources.requests.memory=128Mi

      - name: Run test
        run: |
          mvn verify -P systemtest -pl systemtest -am --no-transfer-progress -Dbasepom.check.skip-coverage=true

      - name: Archive results
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: artifacts
          path: systemtest/target/logs/
