apiVersion: apps/v1
kind: Deployment
metadata:
  name: kas-fleetshard-operator
  labels:
    app: kas-fleetshard-operator
spec:
  replicas: 1
  template:
    metadata:
      name: kas-fleetshard-operator
      labels:
        app: kas-fleetshard-operator
    spec:
      serviceAccountName: kas-fleetshard-operator
      containers:
        - name: kas-fleetshard-operator
          image: ##IMAGE##
          env:
            - name: QUARKUS_PROFILE
              value: prod
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
  selector:
    matchLabels:
      app: kas-fleetshard-operator