apiVersion: v1
kind: ServiceAccount
metadata:
  name: kas-fleetshard-operator
  labels:
    app: kas-fleetshard-operator
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kas-fleetshard-operator
  labels:
    app: kas-fleetshard-operator
rules:
  - apiGroups:
      - apiextensions.k8s.io
    resources:
      # the Java operator SDK seems to need listing CRDs
      - customresourcedefinitions
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - managedkafka.bf2.org
    resources:
      # operator main custom resources for getting Kafka instance to deploy, configuration and reporting back status
      - managedkafkas
      - managedkafkas/status
      - managedkafkaagents
      - managedkafkaagents/status
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - kafka.strimzi.io
    resources:
      # operator creates Kafka custom resource for Strimzi operator and gets the status
      - kafkas
      - kafkas/status
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - apps
      - extensions
    resources:
      # operator creates Deployments for canary and admin server UI
      - deployments
      - deployments/status
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - ""
    resources:
      # the operator creates Services for admin server UI
      - services
      # the operator creates ConfigMaps and Secrets for Kafka metrics configuration and TLS and Keycloak certificates
      - configmaps
      - secrets
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
  - apiGroups:
      - route.openshift.io
    resources:
      # the operator creates a Route for the admin server UI
      - routes
      - routes/custom-host
      - routes/status
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kas-fleetshard-operator
  labels:
    app: kas-fleetshard-operator
subjects:
  - kind: ServiceAccount
    name: kas-fleetshard-operator
    namespace: kas-fleetshard
roleRef:
  kind: ClusterRole
  name: kas-fleetshard-operator
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kas-fleetshard-operator
  labels:
    app: kas-fleetshard-operator
spec:
  replicas: 1
  template:
    metadata:
      name: kas-fleetshard-operator
      labels:
        app: kas-fleetshard-operator
    spec:
      serviceAccountName: kas-fleetshard-operator
      containers:
        - name: kas-fleetshard-operator
          image: ##IMAGE##
          env:
            - name: QUARKUS_PROFILE
              value: prod
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /q/health/live
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          resources:
            limits:
              cpu: 1500m
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
  selector:
    matchLabels:
      app: kas-fleetshard-operator
---